name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  # on pull requests to main branch
  workflow_dispatch:    # manually trigger the workflow

permissions:
  checks: write
  actions: read
  contents: read

jobs:

  build-linux:
    name: Ubuntu-Build
    runs-on: ubuntu-latest

    env:
      PRESET_NAME: gcc-linux-release

    steps:
    - name: Checkout source code
      uses: actions/checkout@v5.0.0

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Cmake configure
      run: cmake --preset ${{ env.PRESET_NAME }} ${{ env.CMAKE_CONFIG_OPTIONS }}

    - name: Cmake build
      run: cmake --build --preset "${{ env.PRESET_NAME }}" -j

    - name: Run Tests
      run: ctest --preset ${{ env.PRESET_NAME }} --output-on-failure

  build-windows:
    name: Windows-Build
    runs-on: windows-2025

    env:
      PRESET_NAME: msvc-win64-release

    steps:
    - name: Checkout source code
      uses: actions/checkout@v5.0.0

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Cmake configure
      run: cmake --preset ${{ env.PRESET_NAME }} ${{ env.CMAKE_CONFIG_OPTIONS }}

    - name: Cmake build
      run: cmake --build --preset "${{ env.PRESET_NAME }}" -j

    - name: Run Tests
      run: ctest --preset ${{ env.PRESET_NAME }} --output-on-failure

  build-macos:
    name: MacOS-Build
    runs-on: macos-15

    env:
      PRESET_NAME: clang-macos-release

    steps:
    - name: Checkout source code
      uses: actions/checkout@v5.0.0

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Cmake configure
      run: cmake --preset ${{ env.PRESET_NAME }} ${{ env.CMAKE_CONFIG_OPTIONS }}

    - name: Cmake build
      run: cmake --build --preset "${{ env.PRESET_NAME }}" -j

    - name: Run Tests
      run: ctest --preset ${{ env.PRESET_NAME }} --output-on-failure
